framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false

    session: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
