<?php

namespace ContainerRDyBJ0N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllersearchByCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rr3BW8T.App\Controller\IndexController::searchByCategory()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rr3BW8T.App\\Controller\\IndexController::searchByCategory()'] = ($container->privates['.service_locator.rr3BW8T'] ?? $container->load('get_ServiceLocator_Rr3BW8TService'))->withContext('App\\Controller\\IndexController::searchByCategory()', $container);
    }
}
