<?php

namespace ContainerRDyBJ0N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s9vRU66.App\Controller\IndexController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s9vRU66.App\\Controller\\IndexController::edit()'] = ($container->privates['.service_locator.s9vRU66'] ?? $container->load('get_ServiceLocator_S9vRU66Service'))->withContext('App\\Controller\\IndexController::edit()', $container);
    }
}
