<?php

namespace ContainerJ9xtAWz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Otz86XrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.otz86Xr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.otz86Xr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\IndexController::index' => ['privates', '.service_locator.rr3BW8T.App\\Controller\\IndexController::index()', 'getIndexControllerindexService', true],
            'App\\Controller\\IndexController::show' => ['privates', '.service_locator.s9vRU66.App\\Controller\\IndexController::show()', 'getIndexControllershowService', true],
            'App\\Controller\\IndexController::edit' => ['privates', '.service_locator.s9vRU66.App\\Controller\\IndexController::edit()', 'getIndexControllereditService', true],
            'App\\Controller\\IndexController::delete' => ['privates', '.service_locator.s9vRU66.App\\Controller\\IndexController::delete()', 'getIndexControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\IndexController:index' => ['privates', '.service_locator.rr3BW8T.App\\Controller\\IndexController::index()', 'getIndexControllerindexService', true],
            'App\\Controller\\IndexController:show' => ['privates', '.service_locator.s9vRU66.App\\Controller\\IndexController::show()', 'getIndexControllershowService', true],
            'App\\Controller\\IndexController:edit' => ['privates', '.service_locator.s9vRU66.App\\Controller\\IndexController::edit()', 'getIndexControllereditService', true],
            'App\\Controller\\IndexController:delete' => ['privates', '.service_locator.s9vRU66.App\\Controller\\IndexController::delete()', 'getIndexControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\IndexController::index' => '?',
            'App\\Controller\\IndexController::show' => '?',
            'App\\Controller\\IndexController::edit' => '?',
            'App\\Controller\\IndexController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\IndexController:index' => '?',
            'App\\Controller\\IndexController:show' => '?',
            'App\\Controller\\IndexController:edit' => '?',
            'App\\Controller\\IndexController:delete' => '?',
        ]);
    }
}
