<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRDyBJ0N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRDyBJ0N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRDyBJ0N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRDyBJ0N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRDyBJ0N\App_KernelDevDebugContainer([
    'container.build_hash' => 'RDyBJ0N',
    'container.build_id' => '5bc03588',
    'container.build_time' => 1777293927,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRDyBJ0N');
