<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPvijiz2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPvijiz2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPvijiz2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPvijiz2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPvijiz2\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pvijiz2',
    'container.build_id' => '52062e64',
    'container.build_time' => 1776610318,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPvijiz2');
