<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5iqflLg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5iqflLg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5iqflLg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5iqflLg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5iqflLg\App_KernelDevDebugContainer([
    'container.build_hash' => '5iqflLg',
    'container.build_id' => '8ec5c5b2',
    'container.build_time' => 1777236050,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5iqflLg');
