<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'article_index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], [], []],
    'article_list' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], [], []],
    'article_save_demo' => [[], ['_controller' => 'App\\Controller\\IndexController::saveDemo'], [], [['text', '/article/save']], [], [], []],
    'article_new' => [[], ['_controller' => 'App\\Controller\\IndexController::new'], [], [['text', '/article/new']], [], [], []],
    'new_category' => [[], ['_controller' => 'App\\Controller\\IndexController::newCategory'], [], [['text', '/category/newCat']], [], [], []],
    'article_search_category' => [[], ['_controller' => 'App\\Controller\\IndexController::searchByCategory'], [], [['text', '/article/search/category']], [], [], []],
    'article_search_price' => [[], ['_controller' => 'App\\Controller\\IndexController::searchByPrice'], [], [['text', '/article/search/price']], [], [], []],
    'article_show' => [['id'], ['_controller' => 'App\\Controller\\IndexController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], [], []],
    'article_edit' => [['id'], ['_controller' => 'App\\Controller\\IndexController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article/edit']], [], [], []],
    'article_delete' => [['id'], ['_controller' => 'App\\Controller\\IndexController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article/delete']], [], [], []],
    'App\Controller\IndexController::saveDemo' => [[], ['_controller' => 'App\\Controller\\IndexController::saveDemo'], [], [['text', '/article/save']], [], [], []],
    'App\Controller\IndexController::new' => [[], ['_controller' => 'App\\Controller\\IndexController::new'], [], [['text', '/article/new']], [], [], []],
    'App\Controller\IndexController::newCategory' => [[], ['_controller' => 'App\\Controller\\IndexController::newCategory'], [], [['text', '/category/newCat']], [], [], []],
    'App\Controller\IndexController::searchByCategory' => [[], ['_controller' => 'App\\Controller\\IndexController::searchByCategory'], [], [['text', '/article/search/category']], [], [], []],
    'App\Controller\IndexController::searchByPrice' => [[], ['_controller' => 'App\\Controller\\IndexController::searchByPrice'], [], [['text', '/article/search/price']], [], [], []],
    'App\Controller\IndexController::show' => [['id'], ['_controller' => 'App\\Controller\\IndexController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], [], []],
    'App\Controller\IndexController::edit' => [['id'], ['_controller' => 'App\\Controller\\IndexController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article/edit']], [], [], []],
    'App\Controller\IndexController::delete' => [['id'], ['_controller' => 'App\\Controller\\IndexController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article/delete']], [], [], []],
];
